### ISSUE TITLE
build_database.py mysql error

### ISSUE THREAD

**Issue by v1nc** [paulpierre/informer#4]
If I try to run `build_database.py`, I get
`sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1049 (42000): Unknown database 'informer_db'`

If I create the db 'informer_db' and run it again, I get
`alchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 1007 (HY000): Can't create database 'informer_db'; database exists`

**Comment by paulpierre** [comment]
Delete the database.

First run build_database.py then run bot.py

build_database.py will auto-generate the database for you

**Comment by 0m3rta13** [comment]
> Delete the database.
> 
> First run build_database.py then run bot.py
> 
> build_database.py will auto-generate the database for you

He is first running build_database.py though? ( according to his post).

Am having the same issue. 
have confirmed everything needed to be filled in is. All the checks i can do to confirm the details entered work.
But when i run build_databases.py i get the error 

`sqlalchemy.exc.ProgrammingError: (mysql.connector.errors.ProgrammingError) 1049 (42000): Unknown database 'informer_db'`

If i create the DB myself i get 

`alchemy.exc.DatabaseError: (mysql.connector.errors.DatabaseError) 1007 (HY000): Can't create database 'informer_db'; database exists`

So build_database.py isnt creating the database nor does it like one created for it.

@v1nc Did you find the problem since you closed the issue? I'm quite sure i must be doing something wrong or missing some detail
